### ISSUE TITLE
FlywayException: Unsupported Database: SQLite 3.40

### ISSUE THREAD

**Issue by TheZappa** [Rakambda/ChannelPointsMiner#383]
### Description

Hi Rakambda,

I have been using your miner for a long time and am very happy with it. Before you switched to using Flyway, the SQLite implementation worked fine. After the change, I have been getting this exception ever since. I tried multiple times to find out what the problem was before making an issue, but my java knowlegde is not good enough to figure it out.

I put it as version 2.1.0, but it's way back when the switch to Flyway happened.

I use the config out of the example folder:
"analytics" : {
            "enabled" : true,
            "database" : {
              "jdbcUrl" : "jdbc:sqlite:miner.db"
        }

I tried running it on a windows and linux environment (both x64) same exception.

If you have anytime to spare to look into this, it would be much appriciated.
If you need anymore information/help or testing on my part let me know!

Sincerly

Zappa

### Version / commit

2.1.0

### Relevant log output

```shell
Exception in thread "main" org.flywaydb.core.api.FlywayException: Unsupported Database: SQLite 3.40
        at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105)
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:76)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:146)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
        at fr.rakambda.channelpointsminer.miner.database.BaseDatabase.applyFlyway(BaseDatabase.java:44)
        at fr.rakambda.channelpointsminer.miner.database.SQLiteDatabase.initDatabase(SQLiteDatabase.java:17)
        at fr.rakambda.channelpointsminer.miner.factory.DatabaseFactory.createDatabase(DatabaseFactory.java:38)
        at fr.rakambda.channelpointsminer.miner.factory.MinerFactory.create(MinerFactory.java:20)
        at fr.rakambda.channelpointsminer.miner.MinerApplication.main(MinerApplication.java:40)
```

**Comment by Rakambda** [comment]
That's rather weird, on my test setup I have sqlite too and I don't see this error.
How do you start the miner (if you can paste the command here would be great)

**Comment by Rakambda** [comment]
I had a similar issue with the shadow jar. To be honest I don't really know what to do with it and how to fix it.

In the meantime there's 2 solutions that I see:
* The most "easiest" one would be to use docker as you don't have to manage the java sersion, gradle etc. Just do some config. However that comes at the cost of knowing docker.
* The other one is to not use the shadow jar and instead tell gradle to run it itself (with something like `gradle :miner:run --args='--settings ../config-test-tv.json'`). That comes at the cost that you need both a JDK + gradle on the machine that'll run the bot, but I guess it's not an issue in your case.

**Comment by Rakambda** [comment]
Can you try with the `fix/shadow-jar` branch, I think it fixes the issue.

**Comment by TheZappa** [comment]
Hey, that did it! Works fine now, I started from a clean database to be safe.

I will definitly try out docker and use that solution if it is easier.

The command I use to start it is the one you put in the documentation with a custom logger config file.

Thanks alot for the fast fix!

I love the miner and looking at how you do your implementation. I'm a .NET developer so this is a nice project to see how java works. I'm very new to gradle, so my general googling was not that strong to begin with. So keep up the good work!
